export const Schema = {
  getStarted: 'getStarted',
  username: 'username',
  password: 'password',
  forgotPassword: 'forgotPassword',
  loginButton: 'loginButton',
  mobileNumber: 'mobileNumber',
  mobileGetOTPBTN: 'mobileGetOTPBTN',
  mapView: 'mapView',
  editProfile: 'editProfile',
  addProfile: 'addProfile',
  notification: 'notification',
  forgotEmail: 'forgotEmail',
  getOTP: 'getOTP',
  emailOTP: 'emailOTP',
  verifyNow: 'verifyNow',
  bikeSelection: 'bikeSelection',
  swipeToStartBike: 'swipeToStartBike',
};
